import Head from 'next/head';
import { ThemeProvider as MuiThemeProvider } from '@mui/material/styles';
import CssBaseline from '@mui/material/CssBaseline';
import { CacheProvider } from '@emotion/react';
import type { EmotionCache } from '@emotion/cache';
import createCache from '@emotion/cache';
import { AppProps } from 'next/app';
import theme from '../src/components/theme';

let muiCache: EmotionCache | undefined = undefined;

export const createMuiCache = () => (muiCache = createCache({ key: 'mui', prepend: true }));

export default function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <CacheProvider value={muiCache ?? createMuiCache()}>
        <MuiThemeProvider theme={theme}>
          <CssBaseline />
          <Component {...pageProps} />
        </MuiThemeProvider>
      </CacheProvider>
    </>
  );
}
